### PR TITLE
optimize Dockerfile

### PR DESCRIPTION
**Pull request by PureWhiteWu**
#46 #66

### CODE REVIEW

**Comment by javasoze** [comment]
dash works, but with logtail, I get:
```
root@1960c53a6a28:/# logtail -a nginx_json@staging.dashbase.io:9876
Traceback (most recent call last):
  File "/usr/local/bin/logtail", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tools/logtail.py", line 55, in main
    t1 = parse(args.time)
  File "/usr/local/lib/python2.7/dist-packages/dateparser/conf.py", line 84, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateparser/__init__.py", line 40, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/usr/local/lib/python2.7/dist-packages/dateparser/date.py", line 371, in get_date_data
    language, date_string, date_formats, settings=self._settings)
  File "/usr/local/lib/python2.7/dist-packages/dateparser/date.py", line 168, in parse
    return instance._parse()
  File "/usr/local/lib/python2.7/dist-packages/dateparser/date.py", line 178, in _parse
    date_obj = parser()
  File "/usr/local/lib/python2.7/dist-packages/dateparser/date.py", line 191, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "/usr/local/lib/python2.7/dist-packages/dateparser/freshness_date_parser.py", line 147, in get_date_data
    date, period = self.parse(date_string, settings)
  File "/usr/local/lib/python2.7/dist-packages/dateparser/freshness_date_parser.py", line 94, in parse
    self.now = datetime.now(self.get_local_tz())
  File "/usr/local/lib/python2.7/dist-packages/dateparser/freshness_date_parser.py", line 46, in get_local_tz
    return get_localzone()
  File "/usr/local/lib/python2.7/dist-packages/tzlocal/unix.py", line 123, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python2.7/dist-packages/tzlocal/unix.py", line 117, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
```

**Comment by javasoze** [comment]
To reproduce:

* clean current images: ```docker rmi -f dashbase/dashbase-tools```
* build image: ```docker build -t dashbase/dashbase-tools . ```
* run image: ``` docker run -it dashbase/dashbase-tools```
* run logtail: ``` logtail -a nginx_json@staging.dashbase.io:9876```

Any reason ci/unittest didn't catch this?

It's good we caught this, is this something we can build into test?

**Comment by PureWhiteWu** [comment]
I found out why.
The `ubuntu:14.04` have timezone default set to `Etc/UTC` in /etc/timezone
The `ubuntu:17.10` don't have this.
So it works on `ubuntu:!4.04` but breaks on `ubuntu:17.10`.
Updating image is really dangerous......
I will change it back to `14.04`.

**Comment by PureWhiteWu** [comment]
Will still have `ruamel.ordereddict not found` error using logtail,  but will be fixed after this is merged because docker build is using the code on develop.

**Pull request merged**
